Add `install-uv` to `update-dependencies`.
This is required now that we do dependency updates with `uv`. Not having `uv` installed is causing the action to fail.

https://github.com/opensafely-core/reports/actions/runs/35577289649/job/106346232357
> Run just update-dependencies
> /usr/bin/env: ‘uvx’: No such file or directory
>  error: Recipe `bump-uv-cutoff` failed with exit code 127

I think that this was missed through oversight in https://github.com/opensafely-core/reports/pull/1149/.

There is such a line in the example that this is based on:
https://github.com/opensafely-core/repo-template/blob/c12f4b44be0de6811979b067cd3cef3913cb635b/.github/workflows/update-dependencies.yml#L20